import { Apartments } from '../search/list-of-apartments/apartments';


export const APARTMENTS: Apartments [] =[
  {
      "id": 1,
      "name": "У катерини василівни",
      "guests": 5,
      "photo": "/assets/img/1.jpg",
      "photo2": "/assets/img/4.jpg",
      "photo3": "/assets/img/2.jpg",
      "photo4": "/assets/img/3.png",
      "adress": {
        "city": "Київ",
        "street": "вул. Шевченка",
        "house": 2,
        "apartment": 14
      },
      "rentType": "Все помешкання",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": true,
        "dishwasher": false,
        "washingMachine": true,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": true,
        "internet": true,
        "tv": false,
        "heating": true,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": true,
        "smokeDetector": true,
      },
      "limitation":  {
        "forBoyOnly": true,
        "forGirlOnly": false,
        "forFamilyOnly": false,
        "withoutChildren": false,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": true,
        "notForForeigners": true,
      },
      "bath": {
        "toilet": true,
        "yardToilet": false,
        "shower": true,
        "jacuzzi": true,
        "pool": true,
      },
      "phoneNumber": "+380981234569",
      "price": 600,
      "about": "Апартаменты имеют большие просторные окна , дизайн в минималистическом стиле, практичный и функциональный.Однокомнатные апартаменты СТУДИИ предлагаются с 2 или 3 спальными местами, гостиной-столовой, мини-кухней: электрической плитой, холодильником и кухонным оборудованием; 2-местная спальная кровать раскладная, возможность 3-го спального места или дивана-кровати; телефон, цветной телевизор, ванная комната с феном, кухонное,  постельное белье и полотенца. Предлагаются Двухкомнатные апартаменты СТУДИИ на 4 спальных места и Двухкомнатные апартаменты CТУДИИ на 5 или 6 спальных мест, которые можно разделить на отдельные спальни раздвижной стенкой, двухярусные кровати и/или откидывающиеся кровати.",
  },{
      "id": 2,
      "name": "У кота Барсика",
      "guests": 2,
      "photo":"/assets/img/2.jpg",
      "photo2": "/assets/img/4.jpg",
      "photo3": "/assets/img/5.jpg",
      "photo4": "/assets/img/1.jpg",
      "adress": {
        "city": "Суми",
        "street": "вул. Шевченка",
        "house": 2,
        "apartment": 4
      },
      "rentType": "Все помешкання",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": true,
        "dishwasher": false,
        "washingMachine": true,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": true,
        "internet": true,
        "tv": false,
        "heating": true,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": true,
        "smokeDetector": false,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": true,
        "forFamilyOnly": false,
        "withoutChildren": true,
        "notForStudents": false,
        "withoutPets": false,
        "notForSmokingPeople": true,
        "notForForeigners": true,
      },
      "bath": {
        "toilet": true,
        "yardToilet": false,
        "shower": true,
        "jacuzzi": true,
        "pool": false,
      },
      "phoneNumber": "+380981234569",
      "price": 600,
      "about": "Апартаменты имеют большие просторные окна , дизайн в минималистическом стиле, практичный и функциональный.Однокомнатные апартаменты СТУДИИ предлагаются с 2 или 3 спальными местами, гостиной-столовой, мини-кухней: электрической плитой, холодильником и кухонным оборудованием; 2-местная спальная кровать раскладная, возможность 3-го спального места или дивана-кровати; телефон, цветной телевизор, ванная комната с феном, кухонное,  постельное белье и полотенца. Предлагаются Двухкомнатные апартаменты СТУДИИ на 4 спальных места и Двухкомнатные апартаменты CТУДИИ на 5 или 6 спальных мест, которые можно разделить на отдельные спальни раздвижной стенкой, двухярусные кровати и/или откидывающиеся кровати.",
  },{
      "id": 3,
      "name": "Логово Дракона",
      "guests": 3,
      "photo": "/assets/img/3.png",
      "photo2": "/assets/img/1.jpg",
      "photo3": "/assets/img/4.jpg",
      "photo4": "/assets/img/5.jpg",
      "adress": {
        "city": "Київ",
        "street": "вул. Соборна",
        "house": 2,
        "apartment": 14
      },
      "rentType": "Кімната",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": false,
        "dishwasher": false,
        "washingMachine": false,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": true,
        "internet": false,
        "tv": false,
        "heating": false,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": false,
        "smokeDetector": false,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": false,
        "forFamilyOnly": false,
        "withoutChildren": false,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": true,
        "notForForeigners": false,
      },
      "bath": {
        "toilet": true,
        "yardToilet": false,
        "shower": true,
        "jacuzzi": false,
        "pool": false,
      },
      "phoneNumber": "+380981234569",
      "price": 500,
      "about": "Апартаменты имеют большие просторные окна , дизайн в минималистическом стиле, практичный и функциональный.Однокомнатные апартаменты СТУДИИ предлагаются с 2 или 3 спальными местами, гостиной-столовой, мини-кухней: электрической плитой, холодильником и кухонным оборудованием; 2-местная спальная кровать раскладная, возможность 3-го спального места или дивана-кровати; телефон, цветной телевизор, ванная комната с феном, кухонное,  постельное белье и полотенца. Предлагаются Двухкомнатные апартаменты СТУДИИ на 4 спальных места и Двухкомнатные апартаменты CТУДИИ на 5 или 6 спальных мест, которые можно разделить на отдельные спальни раздвижной стенкой, двухярусные кровати и/или откидывающиеся кровати.",
  },{
      "id": 4,
      "name": "Кімната привида",
      "guests": 2,
      "photo": "/assets/img/4.jpg",
      "photo2": "/assets/img/1.jpg",
      "photo3": "/assets/img/5.jpg",
      "photo4": "/assets/img/1.jpg",
      "adress": {
        "city": "Суми",
        "street": "вул. Шевченка",
        "house": 2,
        "apartment": 4
      },
      "rentType": "Кімната",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": false,
        "dishwasher": false,
        "washingMachine": true,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": false,
        "internet": true,
        "tv": false,
        "heating": true,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": true,
        "smokeDetector": true,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": false,
        "forFamilyOnly": true,
        "withoutChildren": false,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": false,
        "notForForeigners": false,
      },
      "bath": {
        "toilet": false,
        "yardToilet": true,
        "shower": true,
        "jacuzzi": false,
        "pool": false,
      },
      "phoneNumber": "+380981234569",
      "price": 350,
      "about": "Апартаменты имеют большие просторные окна , дизайн в минималистическом стиле, практичный и функциональный.Однокомнатные апартаменты СТУДИИ предлагаются с 2 или 3 спальными местами, гостиной-столовой, мини-кухней: электрической плитой, холодильником и кухонным оборудованием; 2-местная спальная кровать раскладная, возможность 3-го спального места или дивана-кровати; телефон, цветной телевизор, ванная комната с феном, кухонное,  постельное белье и полотенца. Предлагаются Двухкомнатные апартаменты СТУДИИ на 4 спальных места и Двухкомнатные апартаменты CТУДИИ на 5 или 6 спальных мест, которые можно разделить на отдельные спальни раздвижной стенкой, двухярусные кровати и/или откидывающиеся кровати.",

  },{
      "id": 5,
      "name": "гараж",
      "guests": 3,
      "photo": "/assets/img/5.jpg",
      "photo2": "/assets/img/1.jpg",
      "photo3": "/assets/img/1.jpg",
      "photo4": "/assets/img/1.jpg",
      "adress": {
        "city": "Київ",
        "street": "вул. Соборна",
        "house": 2,
        "apartment": 14
      },
      "rentType": "Кімната",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": true,
        "dishwasher": true,
        "washingMachine": true,
        "microwave": true
      },
      "amenities":  {
        "essentialThings": true,
        "internet": true,
        "tv": true,
        "heating": true,
        "workplace": false,
        "fireplace": false,
        "balcony": true,
        "parkingPlace": false,
        "smokeDetector": false,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": true,
        "forFamilyOnly": false,
        "withoutChildren": true,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": true,
        "notForForeigners": true,
      },
      "bath": {
        "toilet": true,
        "yardToilet": true,
        "shower": true,
        "jacuzzi": false,
        "pool": false,
      },
      "phoneNumber": "+380981234569",
      "price": 350,
      "about": "Апартаменты имеют большие просторные окна , дизайн в минималистическом стиле, практичный и функциональный.Однокомнатные апартаменты СТУДИИ предлагаются с 2 или 3 спальными местами, гостиной-столовой, мини-кухней: электрической плитой, холодильником и кухонным оборудованием; 2-местная спальная кровать раскладная, возможность 3-го спального места или дивана-кровати; телефон, цветной телевизор, ванная комната с феном, кухонное,  постельное белье и полотенца. Предлагаются Двухкомнатные апартаменты СТУДИИ на 4 спальных места и Двухкомнатные апартаменты CТУДИИ на 5 или 6 спальных мест, которые можно разделить на отдельные спальни раздвижной стенкой, двухярусные кровати и/или откидывающиеся кровати.",

  }
];
