import { Apartments } from '../search/list-of-apartments/apartments';


export const APARTMENTS: Apartments [] =[
  {
      "id": 1,
      "name": "У катерини василівни",
      "guests": 5,
      "photo": "/assets/img/1.jpg",
      "photo2": "/assets/img/4.jpg",
      "photo3": "/assets/img/2.jpg",
      "photo4": "/assets/img/3.png",
      "adress": {
        "city": "Київ",
        "street": "вул. Шевченка",
        "house": 2,
        "apartment": 14
      },
      "rentType": "Все помешкання",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": true,
        "dishwasher": false,
        "washingMachine": true,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": true,
        "internet": true,
        "tv": false,
        "heating": true,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": true,
        "smokeDetector": true,
      },
      "limitation":  {
        "forBoyOnly": true,
        "forGirlOnly": false,
        "forFamilyOnly": false,
        "withoutChildren": false,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": true,
        "notForForeigners": true,
      },
      "bath": {
        "toilet": true,
        "yardToilet": false,
        "shower": true,
        "jacuzzi": true,
        "pool": true,
      },
      "lat": 50.389966,
      "lng": 30.441336,
      "phoneNumber": "+380981234569",
      "price": 600,
      "about": "Апартаменты имеют большие просторные окна , дизайн в минималистическом стиле, практичный и функциональный.Однокомнатные апартаменты СТУДИИ предлагаются с 2 или 3 спальными местами, гостиной-столовой, мини-кухней: электрической плитой, холодильником и кухонным оборудованием; 2-местная спальная кровать раскладная, возможность 3-го спального места или дивана-кровати; телефон, цветной телевизор, ванная комната с феном, кухонное,  постельное белье и полотенца. Предлагаются Двухкомнатные апартаменты СТУДИИ на 4 спальных места и Двухкомнатные апартаменты CТУДИИ на 5 или 6 спальных мест, которые можно разделить на отдельные спальни раздвижной стенкой, двухярусные кровати и/или откидывающиеся кровати.",
  },{
      "id": 2,
      "name": "У кота Барсіка",
      "guests": 2,
      "photo":"/assets/img/2.jpg",
      "photo2": "/assets/img/4.jpg",
      "photo3": "/assets/img/5.jpg",
      "photo4": "/assets/img/1.jpg",
      "adress": {
        "city": "Киів",
        "street": "вул. Забайківська",
        "house": 27,
        "apartment": 0,
      },
      "rentType": "Все помешкання",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": true,
        "dishwasher": false,
        "washingMachine": true,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": true,
        "internet": true,
        "tv": false,
        "heating": true,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": true,
        "smokeDetector": false,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": true,
        "forFamilyOnly": false,
        "withoutChildren": true,
        "notForStudents": false,
        "withoutPets": false,
        "notForSmokingPeople": true,
        "notForForeigners": true,
      },
      "bath": {
        "toilet": true,
        "yardToilet": false,
        "shower": true,
        "jacuzzi": true,
        "pool": false,
      },
      "lat": 50.412859,
      "lng": 30.506192,
      "phoneNumber": "+380981234569",
      "price": 600,
      "about": "Апартаменти Апартаменти Kvartira Na Lievom Bierieghu розташовані в районі Дніпровський Києва, приблизно 15 км від аеропорту Zhulhany. У апартаментах передбачено 1 спалень, 1 ванних кімнат і кухню. Апартаменти Апартаменти Kvartira Na Lievom Bierieghu можуть розмістити 3 гостей.",
  },{
      "id": 3,
      "name": "Логово Дракона",
      "guests": 3,
      "photo": "/assets/img/3.png",
      "photo2": "/assets/img/1.jpg",
      "photo3": "/assets/img/4.jpg",
      "photo4": "/assets/img/5.jpg",
      "adress": {
        "city": "Київ",
        "street": "вул. Соборна",
        "house": 2,
        "apartment": 14
      },
      "rentType": "Кімната",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": false,
        "dishwasher": false,
        "washingMachine": false,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": true,
        "internet": false,
        "tv": false,
        "heating": false,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": false,
        "smokeDetector": false,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": false,
        "forFamilyOnly": false,
        "withoutChildren": false,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": true,
        "notForForeigners": false,
      },
      "bath": {
        "toilet": true,
        "yardToilet": false,
        "shower": true,
        "jacuzzi": false,
        "pool": false,
      },
      "lat": 50.422383,
      "lng": 30.524437,
      "phoneNumber": "+380981234569",
      "price": 500,
      "about": "Гості можуть зупинитися в апартаментах Квартира -Апартаменты, обладнаних безкоштовною парковкою, номером для алергіків і місцем для паління. Трансфер з аеропорту, пральня і прасування також доступні.",
  },{
      "id": 4,
      "name": "Кімната привида",
      "guests": 2,
      "photo": "/assets/img/4.jpg",
      "photo2": "/assets/img/1.jpg",
      "photo3": "/assets/img/5.jpg",
      "photo4": "/assets/img/1.jpg",
      "adress": {
        "city": "Київ",
        "street": "пр. Павла Тичини",
        "house": 5,
        "apartment": 44
      },
      "rentType": "Кімната",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": false,
        "dishwasher": false,
        "washingMachine": true,
        "microwave": false
      },
      "amenities":  {
        "essentialThings": false,
        "internet": true,
        "tv": false,
        "heating": true,
        "workplace": false,
        "fireplace": true,
        "balcony": true,
        "parkingPlace": true,
        "smokeDetector": true,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": false,
        "forFamilyOnly": true,
        "withoutChildren": false,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": false,
        "notForForeigners": false,
      },
      "bath": {
        "toilet": false,
        "yardToilet": true,
        "shower": true,
        "jacuzzi": false,
        "pool": false,
      },
      "lat": 50.428021,
      "lng": 30.598764,
      "phoneNumber": "+380981234569",
      "price": 350,
      "about": "Затишна квартира подобово з 4-ма вікнами на пл. Ринок. Інтер’єр квартири виконаний в сучасному стилі. Стилістика відповідають сучасним вимогам комфорту, простоти і функціональності. Розташована в польському будинку з високими стелями і великими вікнами. Всередині будинку знаходиться затишний дворик. Балкон у дворі аптеки-музею. Парадний вхід в під’їзд на кодовому замку. 3-й поверх. Вид з вікон у двір і на вулицю."
  },{
      "id": 5,
      "name": "гараж",
      "guests": 3,
      "photo": "/assets/img/5.jpg",
      "photo2": "/assets/img/1.jpg",
      "photo3": "/assets/img/1.jpg",
      "photo4": "/assets/img/1.jpg",
      "adress": {
        "city": "Київ",
        "street": "вул. Соборна",
        "house": 2,
        "apartment": 14
      },
      "rentType": "Кімната",
      "placeType": "Приватний будинок",
      "beds": 2,
      "kitchenAppliances":  {
        "plate": true,
        "oven": true,
        "dishwasher": true,
        "washingMachine": true,
        "microwave": true
      },
      "amenities":  {
        "essentialThings": true,
        "internet": true,
        "tv": true,
        "heating": true,
        "workplace": false,
        "fireplace": false,
        "balcony": true,
        "parkingPlace": false,
        "smokeDetector": false,
      },
      "limitation":  {
        "forBoyOnly": false,
        "forGirlOnly": true,
        "forFamilyOnly": false,
        "withoutChildren": true,
        "notForStudents": false,
        "withoutPets": true,
        "notForSmokingPeople": true,
        "notForForeigners": true,
      },
      "bath": {
        "toilet": true,
        "yardToilet": true,
        "shower": true,
        "jacuzzi": false,
        "pool": false,
      },
      "lat": 50.481502,
      "lng": 30.467621,
      "phoneNumber": "+380981234569",
      "price": 350,
      "about": "Комфортна 3-х кімнатна квартира з двома роздільними спальнями. Третя кімната невелика, прохідна і може служити для розміщення 5-го гостя.В апартаментах сучасний ремонт. Простора і дуже світла квартира.Вхід в квартиру по балкону з двору. Вид їх вікон на тиху пішохідну вулицю.",

  }
];
